version: "3.8"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: corretoresOnline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/docker_schema.sql:/docker-entrypoint-initdb.d/docker_schema.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:123@db:5432/corretoresOnline?sslmode=disable
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

volumes:
  db_data:
